---
name: release
"on":
  push:
    tags:
      - v*.*.*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          RELEASE_COMMAND: rake release
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        name: Release Gem
        uses: cadwallion/publish-rubygems-action@8f9e0538302643309e4e43bf48cd34173ca48cfc  # yamllint disable-line rule:line-length
